import os
import time
import json
import argparse
from datetime import datetime
from colorama import Fore, Style

def get_directory_tree(root_directory, output_file, exclude=None, json_output=False):
    """Retrieve the directory structure recursively and write it to a file in ASCII format."""
    start_time = time.time()  # Start timing the script execution
    current_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")  # Get current date/time
    exclude = set(exclude) if exclude else set()  # Convert exclude list to a set for fast lookup

    def generate_tree(folder, prefix="", use_colors=True):
        """Recursively generate the ASCII tree structure."""
        entries = sorted(os.listdir(folder))  # Sort for consistent order
        entries = [e for e in entries if not e.startswith(".") and e not in exclude]  # Filter hidden & excluded items

        folder_entries = [e for e in entries if os.path.isdir(os.path.join(folder, e))]
        file_entries = [e for e in entries if os.path.isfile(os.path.join(folder, e))]
        total_entries = len(folder_entries) + len(file_entries)

        if total_entries == 0:
            return [f"{prefix}⚠️ This folder is empty\n"]

        lines = []

        # Iterate through folders
        for index, entry in enumerate(folder_entries):
            is_last = index == (len(folder_entries) + len(file_entries)) - 1
            connector = "└── " if is_last else "├── "
            entry_path = os.path.join(folder, entry)

            folder_name = f"{Fore.BLUE}📂 {entry}/{Style.RESET_ALL}" if use_colors else f"📂 {entry}/"
            lines.append(f"{prefix}{connector}{folder_name}")

            new_prefix = prefix + ("    " if is_last else "│   ")
            lines.extend(generate_tree(entry_path, new_prefix, use_colors))

        # Iterate through files
        for index, entry in enumerate(file_entries):
            is_last = index == len(file_entries) - 1
            connector = "└── " if is_last else "├── "
            entry_path = os.path.join(folder, entry)
            file_size = os.path.getsize(entry_path) / (1024 * 1024)  # Convert to MB

            # Convert to GB if file size > 1024MB
            if file_size > 1024:
                file_size = file_size / 1024
                size_label = f"{file_size:.2f} GB"
            else:
                size_label = f"{file_size:.2f} MB"

            file_entry = f"{Fore.GREEN}📄 {entry} ({size_label}){Style.RESET_ALL}" if use_colors else f"📄 {entry} ({size_label})"
            lines.append(f"{prefix}{connector}{file_entry}")

        return lines

    # Generate tree structure with colors for terminal output
    tree_structure_colored = generate_tree(root_directory, use_colors=True)

    # Generate tree structure without colors for file output
    tree_structure_plain = generate_tree(root_directory, use_colors=False)

    end_time = time.time()  # Stop timing execution
    execution_time = end_time - start_time  # Calculate elapsed time

    # Write to file (without color formatting)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("📂 Directory Structure Report\n")
        f.write("Generated by: Directory Structure Generator\n")
        f.write("Author: yung-megafone\n")
        f.write(f"Generated on: {current_date}\n")
        f.write(f"Execution Time: {execution_time:.2f} seconds\n")
        f.write("-" * 50 + "\n\n")  # Separator
        f.write(f"📂 {os.path.basename(root_directory)}/\n")
        f.write("\n".join(tree_structure_plain) + "\n")

    print(f"Directory structure saved to: {output_file}")

    # Print to terminal with colors
    print("\n".join(tree_structure_colored))

    # JSON Output
    if json_output:
        json_file = output_file.replace(".txt", ".json")
        tree_dict = {"name": os.path.basename(root_directory), "children": tree_structure_plain}
        with open(json_file, "w", encoding="utf-8") as jf:
            json.dump(tree_dict, jf, indent=4)
        print(f"JSON output saved to: {json_file}")

# Command-line argument parsing
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate an ASCII directory structure with file sizes and optional exclusions.")
    parser.add_argument("directory", help="Directory to scan.")
    parser.add_argument("--exclude", nargs="+", help="Folders or file types to exclude", default=[])
    parser.add_argument("--json", action="store_true", help="Output directory structure as JSON")
    
    args = parser.parse_args()
    root_directory = args.directory.strip()
    output_file = "directory_structure.txt"
    
    if os.path.isdir(root_directory):
        get_directory_tree(root_directory, output_file, exclude=args.exclude, json_output=args.json)
    else:
        print("Invalid directory. Please enter a valid path.")